apiVersion: v1
description: A Helm chart for Kubernetes of spring cloud application
icon: https://raw.githubusercontent.com/ica10888/jenkins-x-libraries/master/resources/com/example/springcloud/springcloud.jpg
name: demo
version: 0.1.0
